name: Build & Publish Image to GCR

on:
  push:
    branches:
    - update-workflow

env:
  PROJECT_ID:   hackathon-297608
  GCR_LOCATION: eu.gcr.io
  IMAGE_NAME:   ${{ github.repository }}
  GITHUB_SHA:   ${{ github.sha }}

jobs:
  gcloud-install-build-push-GCR:
    name: Add gcloud, Build & Publish
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Authentication
      uses: google-github-actions/auth@v0.8.0
      with:
        credentials_json: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}

    - name: Setup gcloud cli
      uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        version: '391.0.0'

    - name: Build & Publish
      working-directory: iris
      run: |
        gcloud auth configure-docker
        export TAG=${GCR_LOCATION}/${PROJECT_ID}/$(echo ${IMAGE_NAME,,} | tr '/' '-'):${GITHUB_SHA}
        docker build --tag ${TAG} .
        docker push ${TAG}

